debug mingw path

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -3,9 +3,8 @@ description: "Builds a Tcl extension"
 author: "Ashok P. Nadkarni"
 inputs:
   toolchain:
-    description: "Toolchain - mingw64 or vc. Only used on Windows"
-    required: false
-    default: 'vc'
+    description: "Toolchain - msys2 or vc. Only used on Windows"
+    required: true
   run-tests:
     description: "Whether to run test suite or not"
     required: false
@@ -28,6 +27,15 @@ runs:
   using: 'composite'
   steps:
 
+    # Validation of inputs
+
+    - name: Validate toolchain on Windows
+      if: runner.os == 'windows' && (inputs.toolchain == '' || ! contains('vc,msys2', inputs.toolchain))
+      shell: pwsh
+      run: |
+        echo "::error::Invalid toolchain value (${{ inputs.toolchain }}.) Must be vc or msys2."
+        exit 1
+
     - name: Checkout
       uses: actions/checkout@v4
       with:
@@ -42,7 +50,7 @@ runs:
         nmake /s /f makefile.vc INSTALLDIR=${{ env.TCLDIR }} ${{ inputs.make-opts }}
 
     - name: Build on Windows with MingW64 extension
-      if: runner.os == 'Windows' && inputs.toolchain == 'mingw64'
+      if: runner.os == 'Windows' && inputs.toolchain == 'msys2'
       shell: msys2 {0}
       run: |
         mkdir ${{ runner.temp }}/${{ inputs.build-subdir }}
@@ -69,7 +77,7 @@ runs:
         nmake /s /f makefile.vc INSTALLDIR=${{ env.TCLDIR }} ${{ inputs.test-opts }} test
 
     - name: Test on Unix or MingW64
-      if: (runner.os != 'Windows' || inputs.toolchain == 'mingw64') && inputs.run-tests
+      if: (runner.os != 'Windows' || inputs.toolchain == 'msys2') && inputs.run-tests
       shell: bash
       env:
         ERROR_ON_FAILURES: 1
