Print config log on configure failure

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -58,7 +58,11 @@ runs:
         mkdir -p $BUILDDIR
         cd $BUILDDIR
         echo "Current dir is `pwd`"
-        `cygpath -m "${{ github.workspace }}"`/configure --prefix=${{ env.TCLINSTALLDIR }} --with-tcl=${{ env.TCLINSTALLDIR }}/lib --with-tclinclude=${{ env.TCLINSTALLDIR }}/include ${{ inputs.config-opts }}
+        `cygpath -m "${{ github.workspace }}"`/configure --prefix=${{ env.TCLINSTALLDIR }} --with-tcl=${{ env.TCLINSTALLDIR }}/lib --with-tclinclude=${{ env.TCLINSTALLDIR }}/include ${{ inputs.config-opts }} || {
+           cat config.log
+           echo "::error::Configure failed"
+           exit 1
+        }
         make ${{ inputs.make-opts }}
 
     - name: Build on Unix
@@ -69,7 +73,11 @@ runs:
         echo "BUILDDIR=${BUILDDIR}" >> $GITHUB_ENV
         mkdir -p ${BUILDDIR}
         cd ${BUILDDIR}
-        ${{ github.workspace }}/configure --with-tcl=${{ env.TCLINSTALLDIR }}/lib --with-tclinclude=${{ env.TCLINSTALLDIR }}/include ${{ inputs.config-opts }}
+        ${{ github.workspace }}/configure --with-tcl=${{ env.TCLINSTALLDIR }}/lib --with-tclinclude=${{ env.TCLINSTALLDIR }}/include ${{ inputs.config-opts }} || {
+           cat config.log
+           echo "::error::Configure failed"
+           exit 1
+        }
         make ${{ inputs.make-opts }}
 
     - name: Test with Windows nmake
